### ISSUE TITLE
Cytube user join / leave to an IRC channel

### ISSUE THREAD

**Issue by d-dd** [d-dd/Yukari#39]
Similar to now playing IRC channel, `channel-status` channel will be moderated (+m) and no users except Yukari will have voice. This is meant to be used with a script so there isn't a big focus on message readability.

Yukari will announce:
user part
user join
full userlist*

This channel might be used for other status messages in the future.

*When  yukari joins channel, when IRC gets throttled, when Cytube is under spam and commands are ignored

Clients are responsible for differentiating cytube and irc names and handling name clashes.

For the time being Yukari will use the same nickname as main chat/ now playing.

**Comment by A-t48** [comment]
Woo. Thanks.

**Comment by d-dd** [comment]
Maybe issues in the distant future:
-manage network throttle/anti-flood measures
-multi-line messages. If userlist cannot fit in one IRC line it will just be split into multiple lines (by Twisted's irc client). Clients (user's scripts) may get confused..

**Comment by A-t48** [comment]
The multiline thing does sound like a pain.
